#!/usr/bin/env bash

# archives a project
#
# This will unlink a project from $PROJECTS_PATH

source "${HOME}/.local/lib/log"

ACTIVE_ORGANIZATION="$(cat ${HOME}/.cache/project/organization)"
projects_path=${PROJECTS_PATH:-${HOME}/projects/${ACTIVE_ORGANIZATION}}

# Handle the search term param
if [ ${#} -eq 0 ]; then
  SEARCH_TERM=()
else
  SEARCH_TERM=(-q "${@}")
fi

PROJECTS=$(find "${projects_path}" -maxdepth 1 -mindepth 1 -type l,d -exec basename {} \; | sort | fzf -m --border-label='Projets' "${SEARCH_TERM[@]}")

if [ -z "$PROJECTS" ]; then

  log_info "project" "no project were selected"
  exit 0 # It means we didn't select anything with fzf

else

  # TODO: lock git worktree
  for PROJECT in $PROJECTS; do
    if [ -L "${projects_path}/${PROJECT}" ]; then
      unlink "${projects_path}/${PROJECT}"
      log_info "project" "archived $PROJECT"
    fi

  done
fi
