#!/usr/bin/env bash

# archives a project
#
# This will unlink a project from $PROJECTS_PATH

source ${HOME}/.local/lib/log

projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/subjects}
projects_path=${PROJECTS_PATH:-${HOME}/projects/}

PROJECTS=$(find ${projects_path} -maxdepth 1 -mindepth 1 -type l,d -exec basename {} \;  | sort | fzf -m --border-label='Projets')

if [ -z "$PROJECTS" ]; then

  log_info "project" "no project were selected"
  exit 0 # It means we didn't select anything with fzf

else

  for PROJECT in $PROJECTS; do
    if [ -L ${projects_path}/${PROJECT} ]; then
      unlink ${projects_path}/${PROJECT}
      log_info "project" "archived $PROJECT"
    fi

  done
fi
