#!/usr/bin/env bash

# clones a repo based on clipboard
#
# Using a fzf-based menu, you can select where the
# repo you have in you clipboard will be cloned

source ${HOME}/.local/lib/log
source ${HOME}/.local/lib/clipboard

if [ -f .project ]; then
  source .project
fi

gitrepos="${GIT_REPOS:-$HOME/git/}"
repo_url=$(clip_paste)


DESTINATION="$(find ~/git -maxdepth 3 -mindepth 1 \
    -type d '!' -exec test -e '{}/*/.git' ';' -prune \
    -type d '!' -exec test -e '{}/.git' ';' -prune \
    -type d -print | \
  sort | fzf -m --border-label='Detination')"


if [ -z $PROJECT ]; then
  log_error "project" "PROJECT env variable isn't set"
  exit 1

elif echo $repo_url | grep -v "\.git$"; then
  log_error "project" "clipboard doesn't contain a git url"

fi

if [ -z "$DESTINATION" ]; then
  log_info "project" "nothing was selected"
  exit 0 # It means we didn't select anything with fzf

else
  pushd $DESTINATION > /dev/null
  git clone $(clip_paste) 2> /dev/null
  log_info "project" "git repo cloned in $(pwd)"
  popd > /dev/null

fi
