#!/usr/bin/env bash

# clones a repo based on clipboard
#
# Using a fzf-based menu, you can select where the
# repo you have in you clipboard will be cloned
#

if [ -f .project ]; then
  source .project
fi

gitrepos="${GIT_REPOS}:-$HOME/git/}"

DESTINATION="$(find "$gitrepos" -maxdepth 3 -mindepth 1 -type d | \
  sort | fzf -m --border-label='Detination')"


log() {
  PURPLE='\033[0;35m'
  GREY='\033[0;37m'
  NC='\033[0m' # No Color
  echo -e "${PURPLE}[add-repo]$GREY - $@${NC}"
}

if [ -z $PROJECT ]; then
  log "PROJECT env variable isn't set"
  exit 1
else
  if [ -z "$DESTINATION" ]; then

    exit 0 # It means we didn't select anything with fzf

  else

    pushd $DESTINATION
    git clone $(pbpaste)
    popd
  fi
fi
