#!/usr/bin/env bash

# creates a new project
#
# If lauched with an argument, it will be used to create a project using it as a name
# otherwise you'll be prompted to select a template (if there's any)

source "${HOME}/.local/lib/log"

ACTIVE_ORGANIZATION="$(cat ${HOME}/.cache/project/organization)"
projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/${ACTIVE_ORGANIZATION}}
projects_path=${PROJECTS_PATH:-${HOME}/projects/${ACTIVE_ORGANIZATION}}
projects_templates_path=${PROJECTS_TEMPLATES_PATH:-${HOME}/work/${ACTIVE_ORGANIZATION}/.templates/}

mkdir -p "${projects_path}"

if [ -n "${1}" ]; then
  mkdir -p "${projects_archive}/${1}/.project.d"

else
  if [ -d "${projects_templates_path}" ]; then
    project_template="$(find ${projects_templates_path} -mindepth 1 -maxdepth 1 | sort | fzf --border-label='Project Template' --with-nth '7' --delimiter '/')"

  fi
  # TODO: check if project hasn't already been created yet
  if [ -d ${project_template} ]; then
    pushd ${projects_path}
    cookiecutter ${project_template}
    popd

  else

    log_error "project" "couldn't create project with a template"
    exit 1
  fi
fi

if ln -sf -t "${projects_path}" "${projects_archive}/${1}"; then
  log_info "project" "successfully created project ${1}"
else
  log_error "project" "couldn't create project ${1}"
  exit 1
fi
