#!/usr/bin/env bash

# edits a project source file

source "${HOME}/.local/lib/log"

CURRENT_ORG="$(cat ${HOME}/.cache/project/organization)"
projects_path=${PROJECTS_PATH:-${HOME}/projects/${CURRENT_ORG}}

if $EDITOR "${projects_path}/${PROJECT}/.project.d/zshrc"; then
  log_info "project" "edited project ${PROJECT}"
else
  log_error "project" "couln't edit project ${PROJECT}"
fi
