#!/usr/bin/env bash

# lists available projects
#
# This will either add a git worktree or a link in the
# current project according to the REOP_EXCLUDE_PATTERN

projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/subjects}
projects_path=${PROJECTS_PATH:-${HOME}/projects/}

tree "${projects_path}" -dL 1
tree "${projects_archive}" -dL 1

