#!/usr/bin/env bash

# lists available projects
#
# This will either add a git worktree or a link in the
# current project according to the REOP_EXCLUDE_PATTERN

ACTIVE_ORGANIZATION="$(cat ${HOME}/.cache/project/organization)"
projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/${ACTIVE_ORGANIZATION}}
projects_path=${PROJECTS_PATH:-${HOME}/projects/${ACTIVE_ORGANIZATION}}

tree "${projects_path}" -dL 1
tree "${projects_archive}" -dL 1
