#!/usr/bin/env bash

# unarchives a project
#
# This will link a project from $PROJECTS_ARCHIVE in $PROJECTS_PATH

source "${HOME}/.local/lib/log"

ACTIVE_ORGANIZATION="$(cat ${HOME}/.cache/project/organization)"
projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/${ACTIVE_ORGANIZATION}}
projects_path=${PROJECTS_PATH:-${HOME}/projects/${ACTIVE_ORGANIZATION}}

# Handle the search term param
if [ ${#} -eq 0 ]; then
  SEARCH_TERM=()
else
  SEARCH_TERM=(-q "${@}")
fi

PROJECTS=$(find "${projects_archive}" -maxdepth 1 -mindepth 1 -type l,d -exec basename {} \; | sort | fzf -m --border-label='Projets' "${SEARCH_TERM[@]}")

for PROJECT in ${PROJECTS}; do
  if [ -n "${PROJECT}" ] && ! [ -f "${projects_path}/${PROJECT}" ]; then
    ln -sf -t "${projects_path}" "${projects_archive}/${PROJECT}"
    log_info "project" "unarchived ${PROJECT}"
  fi
done
