# Shell Tools
brew bat
brew catimg
brew exa
brew git-delta
brew jq
brew rg
brew zoxide

# tools
tap ankitpokhrel/jira-cli
brew go
brew jira-cli
brew pgcli
brew pre-commit

# Infrastructure tools
brew flux
brew fluxcd/tap/flux
brew gh
brew krew
brew tfswitch
brew vault

# Fonts
file ~/.config/brewfile/font-taps-Brewfile
brew font-sauce-code-pro-nerd-font
brew --HEAD font-comfortaa
brew --HEAD font-noto-color-emoji

# Mac OS Specific packages (otherwise installed through packages)
file ~/.config/brewfile/mac-Brewfile

