# Shell Tools
brew bat
brew catimg
brew eza
brew git-delta
brew jq
brew pre-commit
brew rg
brew vivid
brew yq
brew zoxide

# tools
tap ankitpokhrel/jira-cli
brew go
brew jira-cli
brew just
brew mise
brew node
brew pgcli
brew pre-commit

# Infrastructure tools
brew gh
brew krew
brew tflint

# Fonts
cask font-sauce-code-pro-nerd-font
cask font-comfortaa
cask font-noto-color-emoji
