#!/usr/bin/env bash

# checks if backups are feasible

source "${HOME}/.local/lib/log"

while getopts r: flag
do
  case "${flag}" in
    r) repo=${OPTARG} ;;
    *) continue ;;
  esac
done

if [ -z "${BORG_REPO}" ]; then
  log_error "backup" "\$BORG_REPO isn't set"
  exit 1
else
  log_debug "backup" "\$BORG_REPO is set"
fi

if [[ "${BORG_REPO}" =~ ^(ssh://[0-9a-z]*(@[0-9a-z]*)?(:[0-9]*)?)?(/[0-9A-Za-z]*)*$ ]]; then
  log_debug "backup" "\$BORG_REPO matches pattern"
else
  log_error "backup" "\$BORG_REPO doesn't match pattern"
  exit 1
fi

if [ -n "${repo}" ]; then
  if borg with-lock "${BORG_REPO}/${repo}" true; then
    log_debug "backup" "host connection is OK"
  else
    log_error "backup" "couldn't connect to host"
    exit 1
  fi
fi
