#!/usr/bin/env bash

# initiates a new borg repo
#
# This will initiate a new borg repository called $BORG_REPO/${name}

source "${HOME}/.local/lib/log"
source "${HOME}/.local/lib/backup"

BACKUP_CONFIG_FILE=${BACKUP_CONFIG_FILE:-~/.config/backups.yaml}

${HOME}/.local/sd/backup/check || exit 1

if [ $# -ne 1 ]; then
  log_error "backup" "wrong number of arguments"
  exit 1
fi

while getopts :a flag
do
  case "${flag}" in
    a)
      all=1
      ;;
    *)
      log_error "backup" "unsupported argument: ${1}"
      ;;
  esac
done

if [ -n "${all}" ]; then
  for repo in $(yq '.backups | keys | .[]' ${BACKUP_CONFIG_FILE}); do
    check_if_declared ${repo} || exit 1
    init_repo ${repo}
  done

else
  repo_name=${1}
  check_if_declared ${repo_name} || exit 1
  init_repo ${repo_name}
fi
