#!/usr/bin/env bash

# restores backups

source "${HOME}/.local/lib/log"
source "${HOME}/.local/lib/backup"

BACKUP_CONFIG_FILE=${BACKUP_CONFIG_FILE:-~/.config/backups.yaml}

if [ $# -ne 3 ]; then
  log_error "backup" "wrong number of arguments"
  exit 1
else
  backup_name=${1}
  archive_name=${2}
  if [ ${3} == "-a" ]; then
    all=1
  else
    path=${3}
  fi
fi

${HOME}/.local/sd/backup/check -r ${backup_name} || exit 1

if [ -n "${all}" ]; then
  restore_archive ${backup_name} ${archive_name}
else
  restore_file ${backup_name} ${archive_name} ${path}
fi
