#!/usr/bin/env bash

# creates a new organization
#
# This will create organization folders in $ORGANIZATIONS
# To remove it use the sd project org remove

source "${HOME}/.local/lib/log"

if [ -n "${1}" ]; then
  ACTIVE_ORGANIZATION="${1}"
else
  log_error "project" "no organization name has been provided"
  exit 1
fi

gitrepos=${GIT_REPOS:-${HOME}/git/${ACTIVE_ORGANIZATION}}
projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/${ACTIVE_ORGANIZATION}}
projects_path=${PROJECTS_PATH:-${HOME}/projects/${ACTIVE_ORGANIZATION}}
projects_cache="${HOME}/.cache/project/${ACTIVE_ORGANIZATION}"

mkdir -p \
  "${projects_cache}" \
  "${projects_path}" \
  "${projects_archive}" \
  "${gitrepos}"
