#!/usr/bin/env bash

# creates a new organization
#
# This will create organization folders in $ORGANIZATIONS
# To remove it use the sd project org remove

source "${HOME}/.local/lib/log"

org_path=${ORG_PATH:-${HOME}/work}

if [ -n "${1}" ]; then
  CURRENT_ORG="${1}"
else
  log_error "project" "no organization name has been provided"
  exit 1
fi

gitrepos=${GIT_REPOS:-${HOME}/git/${CURRENT_ORG}}
projects_archive=${PROJECTS_ARCHIVE:-${HOME}/work/${CURRENT_ORG}}
projects_path=${PROJECTS_PATH:-${HOME}/projects/${CURRENT_ORG}}

mkdir -p \
  "${projects_path}" \
  "${projects_archive}" \
  "${gitrepos}"
