#!/usr/bin/env bash

# switches organizations

# TODO: also switch to last project
# (in the process of adding this feature)

source "${HOME}/.local/lib/log"

org_path=${ORG_PATH:-${HOME}/work}

LOG_FILE="/tmp/${USER}-projectlog"
ACTIVE_ORGANIZATION="${HOME}/.cache/project/organization"

mkdir -p "${HOME}/.cache/project"
ORGANIZATIONS=$(find "${org_path}" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort)

# Handle the search term param
if [ ${#} -eq 0 ]; then
  SEARCH_TERM=()
  ORGANIZATION=$(echo "${ORGANIZATIONS}" | sort | fzf --border-label='Organizations')
else
  SEARCH_TERM=(-q "${@}")
  if [ "$(echo "${ORGANIZATIONS}" | fzf --filter "${@}" | wc -l)" -eq 1 ] && [ ${#} -ne 0 ]; then
    ORGANIZATION=$(echo "${ORGANIZATIONS}" | fzf --filter "${@}")
  else
    ORGANIZATION=$(echo "${ORGANIZATIONS}" | sort | fzf --border-label='Organizations' "${SEARCH_TERM[@]}")
  fi
fi

if [ -n "${ORGANIZATION}" ]; then
  log_info "project" "$(date) setting cache with: ${ORGANIZATION}" >>"${LOG_FILE}"
  echo "${ORGANIZATION}" >"${ACTIVE_ORGANIZATION}"
else
  log_error "project" "$(date) ORGANIZATION variable hasn't been set, staying on ${ACTIVE_ORGANIZATION}" >>"${LOG_FILE}"
  exit 1
fi
