#!/usr/bin/env bash

# clones a repo based on clipboard
#
# Using a fzf-based menu, you can select where the
# repo you have in you clipboard will be cloned

source "${HOME}/.local/lib/log"
source "${HOME}/.local/lib/clipboard"

ACTIVE_ORGANIZATION="$(cat ${HOME}/.cache/project/organization)"
gitrepos=${GIT_REPOS:-${HOME}/git/${ACTIVE_ORGANIZATION}}

repo_url="$(clip_paste)"

if [ -z "${PROJECT}" ]; then
  log_error "project" "PROJECT env variable isn't set"
  exit 1

elif echo "${repo_url}" | grep -qv "\.git$"; then
  log_error "project" "clipboard doesn't contain a git url"
  exit 1

fi

while getopts l:w flag; do
  case "${flag}" in
  l) location=${OPTARG} ;;
  w) create_worktree=1 ;;
  *) continue ;;
  esac
done

if [ -z "${location}" ]; then
  DESTINATION="$(find ${gitrepos} -maxdepth 3 -mindepth 1 \
    -type d '!' -exec test -e '{}/*/.git' ';' -prune \
    -type d '!' -exec test -e '{}/.git' ';' -prune \
    -type d -print |
    sort | fzf -m --border-label='Detination')"
else
  DESTINATION=${location}
fi

if [ -z "${DESTINATION}" ]; then
  log_info "project" "no destination was defined"
  exit 0 # It means we didn't select anything with fzf

else
  pushd "${DESTINATION}" >/dev/null || return
  git clone "$(clip_paste)" 2>/dev/null
  log_info "project" "git repo cloned in $(pwd)"
  popd >/dev/null || return

  repo_args=(-r "${DESTINATION}/$(echo "${repo_url}" | grep -o '/.*\.git' | sed 's/\(\/\|\.git\)//g')")
  if [ -n "${create_worktree}" ]; then
    worktree_arg="-w"
  else
    worktree_arg=""
  fi

  "${SD_ROOT}/project/repo/add" $(echo "${repo_args[@]}" | sed "s|${gitrepos}/||;s/\.git$//;s/\/\//\//g") "${worktree_arg}"
fi
