"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$os\
$username\
[](bg:color_yellow fg:color_bg1)\
$git_state\
$git_status\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
[](fg:color_aqua bg:color_gray)\
$directory\
[](fg:color_gray)\
$kubernetes\
$terraform\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_bg1      = '#3c3836'
color_red      = '#cc241d'
color_green    = '#98971a'
color_yellow   = '#d79921'
color_blue     = '#458588'
color_purple   = '#b16286'
color_aqua     = '#427b58'
color_fg0      = '#fbf1c7'

color_orange   = '#d65d0e'
color_gray     = '#665c54'

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"
format = "[ $symbol]($style)"

[os.symbols]
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Arch = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_gray"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_state]
style = "bg:color_yellow"
format = '[ $state( $progress_current of $progress_total) (fg:color_fg0 bg:color_yellow)]($style)'
rebase = ''
bisect = '󰃻'
cherry_pick = ''

[git_status]
style = "bg:color_yellow"
format = '[[$ahead_behind](fg:color_fg0 bg:color_yellow)]($style)'
ahead = ' ${count} '
diverged = ' ${ahead_count} ${behind_count} '
behind = ' ${count} '

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
ignore_branches = ["linux", "mac-os"]

[kubernetes]
disabled = false
symbol = '󱃾'
style = "fg:color_blue"
format = '[ $symbol $context \($namespace\)]($style)'

[terraform]
disabled = false
style = "fg:color_purple"
format = '[  $version]($style) '

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:color_green)'
error_symbol = '[ ](bold fg:color_red)'
vimcmd_symbol = '[ ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ ](bold fg:color_purple)'
vimcmd_replace_symbol = '[ ](bold fg:color_purple)'
vimcmd_visual_symbol = '[ ](bold fg:color_yellow)'
